CONTAINER Onrpapercutdeformer
{
    NAME Onrpapercutdeformer;
    INCLUDE Obase;

    GROUP ID_OBJECTPROPERTIES
    {
        LONG NR_PAPERCUTDEFORMER_SEED { DEFAULT 42892; STEP 13; }
        LONG NR_PAPERCUTDEFORMER_ITERATIONS { DEFAULT 7; MIN 0; MAX 100; }
    }
}