#ifndef Onrstretchdeformer_H__
#define Onrstretchdeformer_H__

enum
{
  Onrstretchdeformer = 1033758,
  NR_STRETCHDEFORMER_BTN_INITIALIZE = 1002,
  NR_STRETCHDEFORMER_BTN_FREE = 1003,
  NR_STRETCHDEFORMER_INNER_RADIUS = 1000,
  NR_STRETCHDEFORMER_OUTER_RADIUS = 1001,
  NR_STRETCHDEFORMER_FALLOFF_SPLINE = 1005,
  NR_STRETCHDEFORMER_COMPRESS_SPLINE = 1006,
  NR_STRETCHDEFORMER_COMPRESS_STRENGTH = 1004,
  NR_STRETCHDEFORMER_COMPRESS_MAXDISTANCE = 1007,
};

#endif /* Onrstretchdeformer_H__ */